# Generated by Django 2.0.4 on 2018-04-13 23:37

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 13, 23, 37, 11, 786318, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='parent_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Comment'),
        ),
        migrations.AlterField(
            model_name='content',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 13, 23, 37, 11, 785316, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='rate',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 13, 23, 37, 11, 786318, tzinfo=utc)),
        ),
    ]
