# Generated by Django 2.0.4 on 2018-04-11 16:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 11, 16, 43, 5, 970961, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='content',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 11, 16, 43, 5, 970961, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(null=True, verbose_name='Date of Birth'),
        ),
    ]
